KIK-8292 Add tests for consecutive transactions
kinfoundation/kin-sdk-core-ios pull request #76
Opened 2017-11-28 10:27 UTC by natanrolnik

And also with wrong/empty password in the 2nd try.

2017-11-28 11:30 UTC, avi-kik commented
This will have to updated after my PR is merged.

2017-11-28 13:29 UTC, Elaz requested changes

2017-11-28 13:29 UTC, Elaz commented on KinSDK/KinSDKTests/KinAccountTests.swift
> +            XCTAssertEqual(nsError.localizedDescription, "could not decrypt key with given passphrase")
if geth did actually localize anything in their error messages, this would fail on machines with non us region.

2017-11-29 12:32 UTC, avi-kik commented on KinSDK/KinSDKTests/KinAccountTests.swift
> +    func test_consecutive_send_transactions() {
What is this testing?  It's not one of the tests requested in the ticket.

2017-11-29 12:32 UTC, avi-kik commented on KinSDK/KinSDKTests/KinAccountTests.swift
> +    func test_send_transaction_with_wrong_passphrase_after_successful_send() {
What is this testing? It's not one of the tests requested in the ticket.

2017-12-10 11:44 UTC, closed without merging